# Generated by Django 3.2.3 on 2021-08-10 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_status', models.CharField(choices=[('in-progress', 'in-progress'), ('done', 'done'), ('todo', 'todo')], default='todo', max_length=15)),
                ('is_trashed', models.BooleanField(default=False)),
                ('date_created', models.DateField()),
                ('last_updated', models.DateField()),
                ('is_archived', models.BooleanField(default=False)),
                ('schedule_on', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
